package provider

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

const testLocaleResource = "sysutils_locale.test"

func localeResourceConfig(root, attrs string) string {
	p := ""
	if root != "" {
		p = rootedProvider(root)
	}
	return p + fmt.Sprintf(`
resource "sysutils_locale" "test" {
%s
}
`, attrs)
}

func TestAccLocale_rootDirDebian(t *testing.T) {
	root := testRootDir(t)
	mustWrite(t, filepath.Join(root, "etc/debian_version"), "12.5\n")
	p := filepath.Join(root, "etc/default/locale")
	const orig = "#  File generated by update-locale\nLANG=\"C.UTF-8\"\nLANGUAGE=en_US:en\n"
	mustWrite(t, p, orig)
	mustChmod(t, p, 0o640)
	config := func(attrs string) string {
		return localeResourceConfig(root, "  restore_on_destroy = true\n"+attrs)
	}

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		// Destroy puts back the LANG and LC_* assignments, not the rest of
		// the file, which was deleted and recreated by the steps below.
		CheckDestroy: checkFileContent(p, "LANG=C.UTF-8\n"),
		Steps: []resource.TestStep{
			{
				Config: config(`  lang = "en_US.UTF-8"
  lc = {
    LC_TIME  = "en_GB.UTF-8"
    LC_PAPER = "de_DE.UTF-8"
  }`),
				Check: resource.ComposeAggregateTestCheckFunc(
					checkFileContent(p, "#  File generated by update-locale\nLANG=en_US.UTF-8\nLANGUAGE=en_US:en\nLC_TIME=en_GB.UTF-8\nLC_PAPER=de_DE.UTF-8\n"),
					checkFileMode(p, 0o640),
					checkNoTempFiles(filepath.Dir(p)),
					resource.TestCheckResourceAttr(testLocaleResource, "id", "system"),
					resource.TestCheckResourceAttr(testLocaleResource, "path", "/etc/default/locale"),
					resource.TestCheckResourceAttr(testLocaleResource, "generate", "false"),
					resource.TestCheckResourceAttr(testLocaleResource, "lc.%", "2"),
				),
			},
			{
				Config: config(`  lang = "en_US.UTF-8"
  lc = {
    LC_TIME  = "en_GB.UTF-8"
    LC_PAPER = "de_DE.UTF-8"
  }`),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{plancheck.ExpectEmptyPlan()},
				},
			},
			{
				// Changed outside Terraform: LANG edited, LC_ALL added.
				PreConfig: setFile(t, p, "LANG=de_DE.UTF-8\nLANGUAGE=en_US:en\nLC_TIME=en_GB.UTF-8\nLC_PAPER=de_DE.UTF-8\nLC_ALL=C\n"),
				Config: config(`  lang = "en_US.UTF-8"
  lc = {
    LC_TIME  = "en_GB.UTF-8"
    LC_PAPER = "de_DE.UTF-8"
  }`),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{plancheck.ExpectResourceAction(testLocaleResource, plancheck.ResourceActionUpdate)},
				},
				Check: checkFileContent(p, "LANG=en_US.UTF-8\nLANGUAGE=en_US:en\nLC_TIME=en_GB.UTF-8\nLC_PAPER=de_DE.UTF-8\n"),
			},
			{
				// Removing lc removes the LC_* variables.
				Config: config(`  lang = "de_DE.UTF-8"`),
				Check: resource.ComposeAggregateTestCheckFunc(
					checkFileContent(p, "LANG=de_DE.UTF-8\nLANGUAGE=en_US:en\n"),
					resource.TestCheckNoResourceAttr(testLocaleResource, "lc.%"),
				),
			},
			{
				// The file was deleted.
				PreConfig: func() { _ = os.Remove(p) },
				Config:    config(`  lang = "de_DE.UTF-8"`),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{plancheck.ExpectResourceAction(testLocaleResource, plancheck.ResourceActionUpdate)},
				},
				Check: checkFileContent(p, "LANG=de_DE.UTF-8\n"),
			},
			{
				Config:                  config(`  lang = "de_DE.UTF-8"`),
				ResourceName:            testLocaleResource,
				ImportState:             true,
				ImportStateId:           "system",
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"restore_on_destroy"},
			},
		},
	})
}

// TestAccLocale_createsFile creates /etc/locale.conf in a tree without one,
// and removes it again on destroy with restore_on_destroy.
func TestAccLocale_createsFile(t *testing.T) {
	root := testRootDir(t)
	p := filepath.Join(root, "etc/locale.conf")
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             checkNotExist(p),
		Steps: []resource.TestStep{
			{
				Config: localeResourceConfig(root, "  lang = \"C.UTF-8\"\n  lc = {}\n  restore_on_destroy = true"),
				Check: resource.ComposeAggregateTestCheckFunc(
					checkFileContent(p, "LANG=C.UTF-8\n"),
					checkFileMode(p, 0o644),
					resource.TestCheckResourceAttr(testLocaleResource, "path", "/etc/locale.conf"),
					resource.TestCheckResourceAttr(testLocaleResource, "lc.%", "0"),
				),
			},
			{
				// An empty lc map stays empty.
				Config: localeResourceConfig(root, "  lang = \"C.UTF-8\"\n  lc = {}\n  restore_on_destroy = true"),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{plancheck.ExpectEmptyPlan()},
				},
			},
		},
	})
}

// TestAccLocale_explicitPath writes the configured file, leaves it on
// destroy, and forces a new resource when path changes.
func TestAccLocale_explicitPath(t *testing.T) {
	root := testRootDir(t)
	mustWrite(t, filepath.Join(root, "etc/locale.conf"), "LANG=C\n")
	a := filepath.Join(root, "etc/default/locale")
	b := filepath.Join(root, "etc/locale.conf")
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             checkFileContent(b, "LANG=en_US.UTF-8\n"),
		Steps: []resource.TestStep{
			{
				Config: localeResourceConfig(root, "  lang = \"en_US.UTF-8\"\n  path = \"/etc/default/locale\""),
				Check: resource.ComposeAggregateTestCheckFunc(
					checkFileContent(a, "LANG=en_US.UTF-8\n"),
					checkFileContent(b, "LANG=C\n"),
				),
			},
			{
				Config: localeResourceConfig(root, "  lang = \"en_US.UTF-8\"\n  path = \"/etc/locale.conf\""),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{plancheck.ExpectResourceAction(testLocaleResource, plancheck.ResourceActionDestroyBeforeCreate)},
				},
				Check: resource.ComposeAggregateTestCheckFunc(
					checkFileContent(a, "LANG=en_US.UTF-8\n"),
					checkFileContent(b, "LANG=en_US.UTF-8\n"),
				),
			},
		},
	})
}

func TestAccLocale_errors(t *testing.T) {
	root := testRootDir(t)
	mustMkdir(t, filepath.Join(root, "etc"))
	target := filepath.Join(root, "target")
	mustWrite(t, target, "LANG=C\n")
	mustSymlink(t, "/target", filepath.Join(root, "etc/locale.conf"))
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config:      localeResourceConfig(root, `  lang = "en_US.UTF-8\nLC_ALL=C"`),
				ExpectError: regexp.MustCompile(`must\s+be\s+a\s+locale\s+name`),
			},
			{
				Config:      localeResourceConfig(root, "  lang = \"C\"\n  lc = { LC_ALL = \"C\" }"),
				ExpectError: regexp.MustCompile(`not\s+a\s+locale\s+category\s+variable`),
			},
			{
				Config:      localeResourceConfig(root, "  lang = \"C\"\n  lc = { LC_TIME = \"$(id)\" }"),
				ExpectError: regexp.MustCompile(`must\s+be\s+a\s+locale\s+name`),
			},
			{
				Config:      localeResourceConfig(root, "  lang = \"C\"\n  generate = true"),
				ExpectError: regexp.MustCompile(`(?s)Not\s+supported\s+with\s+root_dir`),
			},
			{
				// A symlink at the path is refused.
				Config:      localeResourceConfig(root, `  lang = "C"`),
				ExpectError: regexp.MustCompile(`is\s+a\s+symbolic\s+link;\s+refusing\s+to\s+follow\s+it`),
			},
			{
				Config:        localeResourceConfig(root, `  lang = "C"`),
				ResourceName:  testLocaleResource,
				ImportState:   true,
				ImportStateId: "/etc/locale.conf",
				ExpectError:   regexp.MustCompile(`import\s+ID\s+of\s+sysutils_locale\s+must\s+be\s+"system"`),
			},
		},
	})
	if err := checkFileContent(target, "LANG=C\n")(nil); err != nil {
		t.Error(err)
	}
}

// TestAccLocale_generateFake generates missing locales with a fake
// locale-gen, writing the locale file to a temporary path on the host root.
func TestAccLocale_generateFake(t *testing.T) {
	f := newFakeLocaleTools(t, "locale", "locale-gen", "localedef")
	gen := filepath.Join(f.etcDir, "locale.gen")
	mustWrite(t, gen, "# en_US.UTF-8 UTF-8\n# en_GB.UTF-8 UTF-8\n")
	p := filepath.Join(t.TempDir(), "locale.conf")
	factories := map[string]func() (tfprotov6.ProviderServer, error){
		"sysutils": providerserver.NewProtocol6WithError(&sysutilsProvider{version: "test", locale: f.config()}),
	}
	config := func(generate bool) string {
		return localeResourceConfig("", fmt.Sprintf("  path = %q\n  lang = \"en_US.UTF-8\"\n  lc = { LC_TIME = \"en_GB.UTF-8\" }\n  generate = %t", p, generate))
	}
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: factories,
		Steps: []resource.TestStep{
			{
				// Without generate, a missing locale is only a warning.
				Config: config(false),
				Check: resource.ComposeAggregateTestCheckFunc(
					checkFileContent(p, "LANG=en_US.UTF-8\nLC_TIME=en_GB.UTF-8\n"),
					checkFileContent(gen, "# en_US.UTF-8 UTF-8\n# en_GB.UTF-8 UTF-8\n"),
				),
			},
			{
				Config: config(true),
				Check: resource.ComposeAggregateTestCheckFunc(
					checkFileContent(gen, "en_US.UTF-8 UTF-8\nen_GB.UTF-8 UTF-8\n"),
					func(*terraform.State) error {
						f.mu.Lock()
						defer f.mu.Unlock()
						n := 0
						for _, c := range f.calls {
							if c[0] == "locale-gen" {
								n++
							}
						}
						if n != 1 {
							return fmt.Errorf("locale-gen ran %d times, want once: %q", n, f.calls)
						}
						return nil
					},
				),
			},
			{
				// Installed now: nothing is generated again.
				Config: config(true),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{plancheck.ExpectEmptyPlan()},
				},
			},
		},
	})
}

// requireHostLocaleFile skips the test unless it may change the locale
// configuration of the real host, and returns the host's locale file,
// whose content is put back when the test ends.
func requireHostLocaleFile(t *testing.T) (p string, orig *string) {
	t.Helper()
	if os.Getenv("TF_ACC") == "" {
		t.Skip("acceptance test; set TF_ACC=1 to run")
	}
	requireRoot(t)
	p, err := detectLocalePath(hostRoot)
	if err != nil {
		t.Skipf("cannot detect the locale file: %v", err)
	}
	data, _, err := readRegularFileNoFollow(p, maxLocaleFileSize)
	switch {
	case errors.Is(err, os.ErrNotExist):
	case err != nil:
		t.Skipf("cannot read %s: %v", p, err)
	default:
		s := string(data)
		orig = &s
	}
	t.Cleanup(func() {
		var err error
		if orig == nil {
			if err = os.Remove(p); errors.Is(err, os.ErrNotExist) {
				err = nil
			}
		} else if cur, rerr := os.ReadFile(p); rerr != nil || string(cur) != *orig {
			err = os.WriteFile(p, []byte(*orig), 0o644)
		}
		if err != nil {
			t.Errorf("restoring %s: %v", p, err)
		}
	})
	return p, orig
}

// TestAccLocale_realHost sets the locale of the machine running the test to
// C.UTF-8, which glibc has built in, and restores it on destroy.
func TestAccLocale_realHost(t *testing.T) {
	p, orig := requireHostLocaleFile(t)
	check := func(*terraform.State) error {
		data, err := os.ReadFile(p)
		switch {
		case orig == nil && errors.Is(err, os.ErrNotExist):
			return nil
		case orig == nil:
			return fmt.Errorf("%s exists after destroy (%v)", p, err)
		case err != nil:
			return err
		}
		// Only the assignments are restored; quoting may differ.
		if got, want := readLocaleVars(parseTextFile(data).lines), readLocaleVars(parseTextFile([]byte(*orig)).lines); !mapsEqual(got, want) {
			return fmt.Errorf("%s assigns %v after destroy, want %v", p, got, want)
		}
		return nil
	}
	config := localeResourceConfig("", "  lang = \"C.UTF-8\"\n  lc = { LC_MESSAGES = \"C.UTF-8\" }\n  restore_on_destroy = true")
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		CheckDestroy:             check,
		Steps: []resource.TestStep{
			{
				Config: config,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr(testLocaleResource, "path", p),
					func(*terraform.State) error {
						data, err := os.ReadFile(p)
						if err != nil {
							return err
						}
						vars := readLocaleVars(parseTextFile(data).lines)
						if vars["LANG"] != "C.UTF-8" || vars["LC_MESSAGES"] != "C.UTF-8" || len(vars) != 2 {
							return fmt.Errorf("%s assigns %v", p, vars)
						}
						return nil
					},
				),
			},
			{
				Config: config,
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{plancheck.ExpectEmptyPlan()},
				},
			},
		},
	})
}

func mapsEqual(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if w, ok := b[k]; !ok || w != v {
			return false
		}
	}
	return true
}

// accGenerateLocale is the locale TestAccLocale_realHostGenerate compiles:
// in every glibc, and rarely installed.
const accGenerateLocale = "en_DK.UTF-8"

// TestAccLocale_realHostGenerate compiles a locale on the machine running
// the test with the real locale-gen or localedef. The locale file is a
// temporary one; /etc/locale.gen is restored and the compiled locale
// removed when the test ends. It skips itself if the locale is installed
// already, so that it never removes a locale the host uses.
func TestAccLocale_realHostGenerate(t *testing.T) {
	if os.Getenv("TF_ACC") == "" {
		t.Skip("acceptance test; set TF_ACC=1 to run")
	}
	requireRoot(t)
	cfg := &localeConfig{}
	ctx := context.Background()
	installed, err := cfg.available(ctx)
	if err != nil {
		t.Skipf("cannot list locales: %v", err)
	}
	if len(missingLocales(installed, []string{accGenerateLocale})) == 0 {
		t.Skipf("%s is installed already", accGenerateLocale)
	}
	_, lgErr := os.Stat(localeGenPath)
	useLocaleGen := lgErr == nil && cfg.look("locale-gen") == nil
	if !useLocaleGen {
		if cfg.look("localedef") != nil {
			t.Skip("neither locale-gen nor localedef is installed")
		}
		if _, err := os.Stat("/usr/share/i18n/locales/en_DK"); err != nil {
			t.Skipf("the glibc locale sources are not installed: %v", err)
		}
	}
	if gen, err := os.ReadFile(localeGenPath); err == nil {
		t.Cleanup(func() {
			if err := os.WriteFile(localeGenPath, gen, 0o644); err != nil {
				t.Errorf("restoring %s: %v", localeGenPath, err)
			}
			if useLocaleGen {
				if out, err := exec.Command("locale-gen").CombinedOutput(); err != nil {
					t.Errorf("locale-gen: %v: %s", err, out)
				}
			}
		})
	}
	t.Cleanup(func() {
		// Compiled into the archive or into a directory, depending on the
		// distribution.
		name := normalizeLocaleName(accGenerateLocale)
		_ = exec.Command("localedef", "--delete-from-archive", name).Run()
		_ = os.RemoveAll(filepath.Join("/usr/lib/locale", name))
	})

	p := filepath.Join(t.TempDir(), "locale.conf")
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: localeResourceConfig("", fmt.Sprintf("  path = %q\n  lang = %q\n  generate = true", p, accGenerateLocale)),
				Check: resource.ComposeAggregateTestCheckFunc(
					checkFileContent(p, "LANG="+accGenerateLocale+"\n"),
					func(*terraform.State) error {
						out, err := exec.Command("locale", "-a").Output()
						if err != nil {
							return err
						}
						if !slices.Contains(splitLines(string(out)), normalizeLocaleName(accGenerateLocale)) {
							return fmt.Errorf("locale -a does not list %s:\n%s", accGenerateLocale, out)
						}
						return nil
					},
				),
			},
		},
	})
}

func splitLines(s string) []string {
	var lines []string
	for _, l := range regexp.MustCompile(`\r?\n`).Split(s, -1) {
		if l != "" {
			lines = append(lines, l)
		}
	}
	return lines
}
